// <auto-generated />
namespace SistemadeCompras.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class articulo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(articulo));
        
        string IMigrationMetadata.Id
        {
            get { return "201910292232152_articulo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
